stages:
  - validate
  - lint

validate_yaml:
  stage: validate
  image: alpine
  script:
    - apk add --no-cache yamllint
    - yamllint values-prod.yaml
  only:
    - main

helm_lint:
  stage: validate
  image: alpine/helm:3.14.4
  script:
    - helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
    - helm repo update
    - helm lint prometheus-community/kube-prometheus-stack -f values-prod.yaml
  only:
    - main

lint_scripts:
  stage: lint
  image: koalaman/shellcheck-alpine
  script:
    - shellcheck k3s-bootstrap.sh uninstall.sh || true
  only:
    - main

mock_deploy_log:
  stage: lint
  image: alpine
  script:
    - echo "This step simulates local deploy via deploy-local.sh"
    - echo "To test manually: bash scripts/deploy-local.sh"
  only:
    - main
